[tool.poetry]
name = "srt-parse"
version = "0.1.0"
description = ""
authors = ["Jeff Brennan <jeffbrennan10@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
polars = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
